# Generated by Django 5.1.1 on 2024-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('assignDate', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
